// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHdtfhqPXK3qAvbXMMdKQ2xLSkZUD0Wc4',
    appId: '1:500815262323:web:a407e73584545a62da7006',
    messagingSenderId: '500815262323',
    projectId: 'graduationproject-e52ee',
    authDomain: 'graduationproject-e52ee.firebaseapp.com',
    storageBucket: 'graduationproject-e52ee.firebasestorage.app',
    measurementId: 'G-TLPMX52ZYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNM5HnU4UGzMm0LRmo3_lp1Ox5slcpgsY',
    appId: '1:500815262323:android:7ba1c7e82ad252f0da7006',
    messagingSenderId: '500815262323',
    projectId: 'graduationproject-e52ee',
    storageBucket: 'graduationproject-e52ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvrQ3dOrUN9eTZNoJFVeFwHolnfumfGAk',
    appId: '1:500815262323:ios:e5a092885cda90fbda7006',
    messagingSenderId: '500815262323',
    projectId: 'graduationproject-e52ee',
    storageBucket: 'graduationproject-e52ee.firebasestorage.app',
    iosBundleId: 'com.example.projectgraduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvrQ3dOrUN9eTZNoJFVeFwHolnfumfGAk',
    appId: '1:500815262323:ios:e5a092885cda90fbda7006',
    messagingSenderId: '500815262323',
    projectId: 'graduationproject-e52ee',
    storageBucket: 'graduationproject-e52ee.firebasestorage.app',
    iosBundleId: 'com.example.projectgraduation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHdtfhqPXK3qAvbXMMdKQ2xLSkZUD0Wc4',
    appId: '1:500815262323:web:fc0217ab2ca77db6da7006',
    messagingSenderId: '500815262323',
    projectId: 'graduationproject-e52ee',
    authDomain: 'graduationproject-e52ee.firebaseapp.com',
    storageBucket: 'graduationproject-e52ee.firebasestorage.app',
    measurementId: 'G-4S2LVJ517D',
  );
}
